name: medika
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  table_calendar: ^3.0.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.6.1

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/Group.png
    - assets/images/Group_2.png
    - assets/images/Frame.png
    - assets/images/Soue.jpg
    - assets/icons/Care.png
    - assets/icons/Doctor.png
    - assets/icons/Hospital.png
    - assets/icons/Pharmacy.png
    - assets/images/icons/logo.png
    - assets/images/icons/therapyLogoWhite.png
    - assets/images/icons/om.png
    - assets/images/icons/drMeetLogoWhite.png
    - assets/images/icons/profilePhoto.png
    - assets/images/icons/pharmax.png
    - assets/images/doctor.png
    - assets/images/onBoard1.png
    - assets/images/onBoard2.png
    - assets/images/onBoard3.png
    - assets/images/onBoard4.png
    - assets/images/onBoard5.png
    - assets/images/onBoard6.png
    - assets/images/onBoard6.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100


